name: Download Release Assets
description: Download release assets matching a pattern.

inputs:
  pattern:
    description: Pattern to match files
    required: true
    default: '*'
  release-id:
    description: Release ID
    required: true
  token:
    description: GitHub token
    required: true
  path:
    description: Path for downloaded assets
    required: true
  verbose:
    description: Enable verbose tracing
    required: false
    default: false

runs:
  using: composite
  steps:
    - run: |
        echo "1. Downloading assets for release $env:__RELEASE_ID"
        ./download-assets.ps1 `
        -pattern $env:__PATTERN `
        -token $env:__TOKEN `
        -outputPath $env:__OUTPUT_PATH `
        -releaseId $env:__RELEASE_ID `
        ${{ (inputs.VERBOSE || env.ACTIONS_RUNNER_DEBUG == 'true') && '-Verbose' || '' }}
      id: download-assets
      shell: pwsh
      working-directory: ${{ github.action_path }}
      env:
        __PATTERN: ${{ inputs.pattern }}
        __TOKEN: ${{ inputs.token }}
        __OUTPUT_PATH: ${{ inputs.path }}
        __RELEASE_ID: ${{ inputs.release-id }}
