name: 📑 .NET docfx Build and Deploy

on:
  workflow_call:
    inputs:
      environment:
        description: Environment to build
        type: string
        required: true
        default: 'github-pages'
      dotnet-version:
        description: .NET version to use or 'global' to use global.json
        type: string
        required: false
        default: '8.x.x'

permissions:
  actions: read
  pages: write
  id-token: write

jobs:
  publish-docs:
    environment:
      name: ${{ inputs.environment }}
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      page_url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # avoid shallow clone so nbgv can do its work.
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      if: ${{ inputs.dotnet-version == 'global' }}
      with:
        global-json-file: ./global.json
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      if: ${{ inputs.dotnet-version != 'global' }}
      with:
        dotnet-version: ${{ inputs.dotnet-version }}
      env:
        DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    
    - name: Nerdbank.GitVersioning
      uses: dotnet/nbgv@v0.4.2
      with:
        setCommonVars: true
      id: nbgv
    
    - name: Install tools
      run: dotnet tool restore
    
    - name: Generate documentation
      run: dotnet docfx docfx/docfx.json
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docfx/_site
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
