name: ⚒️ .NET Cross-Platform CI

on:
  workflow_call:
    inputs:
      configuration:
        description: Configuration to build
        type: string
        required: true
        default: 'Release'
      dotnet-verbosity:
        description: Verbosity for dotnet
        type: string
        required: false
        default: 'normal'
      push-to-github:
        description: Push to GitHub package feed
        type: boolean
        required: true
        default: true
      prepare-draft-release:
        description: Prepare draft release
        type: boolean
        required: true
        default: true
    secrets:
      CODECOV_TOKEN:
        required: false

jobs:
  os:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            coverage: true
            pack:     true
            push-github: ${{ inputs.push-to-github }}
            draft-release: ${{ inputs.prepare-draft-release }}
          - os: windows-latest
            coverage: false
            pack:     false
            push-github: false
            draft-release: false
          - os: macos-latest
            coverage: false
            pack:     false
            push-github: false
            draft-release: false
    uses: libanvl/ci/.github/workflows/dotnet-ci-os@main
    with:
      os: ${{ matrix.os }}
      configuration: ${{ inputs.configuration }}
      dotnet-verbosity: ${{ inputs.dotnet-verbosity }}
      coverage: ${{ matrix.coverage }}
      pack: ${{ matrix.pack }}
      push-github: ${{ matrix.push-github }}
      draft-release: ${{ matrix.draft-release }}
    secrets: inherit